# Generated by Django 4.2.2 on 2023-11-03 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0101_specification_size_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_gallery'),
        ),
    ]
