# Generated by Django 4.2.2 on 2023-11-03 22:52

from django.db import migrations, models
import userauths.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0102_color_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.FileField(blank=True, default='brand.jpg', null=True, upload_to='brand'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.FileField(blank=True, default='category.jpg', null=True, upload_to='category'),
        ),
        migrations.AlterField(
            model_name='color',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='product_gallery'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.FileField(default='gallery.jpg', upload_to='product_gallery'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(default='product.jpg', upload_to=userauths.models.user_directory_path),
        ),
    ]
