# Generated by Django 5.0 on 2023-12-24 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0103_alter_brand_image_alter_category_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Paypal', 'Paypal'), ('Credit/Debit Card', 'Credit/Debit Card'), ('Wallet Points', 'Wallet Points'), ('Cash On Delivery', 'Cash On Delivery')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('processing', 'Processing'), ('cancelled', 'Cancelled'), ('initiated', 'Initiated'), ('failed', 'failed'), ('refunding', 'refunding'), ('refunded', 'refunded'), ('unpaid', 'unpaid'), ('expired', 'expired'), ('cash_on_delivery_pending', 'cash On Delivery Pending')], default='initiated', max_length=100),
        ),
    ]
